<a href="https://colab.research.google.com/github/addulamalerupareddy-gif/Data-Analatics/blob/main/numpytask03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([100, 200, 300, 400, 500])
print("First two elements:", A[0:2])
print("Last three elements:", A[-3:])
print("Middle element:", A[2])

First two elements: [100 200]
Last three elements: [300 400 500]
Middle element: 300


In [3]:
A = np.array([2, 4, 6, 8, 10, 12, 14])

print(A[1:-1])

[ 4  6  8 10 12]


In [5]:
M = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print("Sub-matrix:")
print(M[0:2, 1:3])

print("Last row:")
print(M[-1, :])

print("First column:")
print(M[:, 0])

Sub-matrix:
[[20 30]
 [60 70]]
Last row:
[ 90 100 110 120]
First column:
[10 50 90]


In [6]:
(4)
A = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(A[::3])

[1 4 7]


PART:B Boolean Filtering

In [7]:
(5)
A = np.array([5, 12, 17, 3, 8, 20])

print("Values > 10:", A[A > 10])
print("Values <= 8:", A[A <= 8])

Values > 10: [12 17 20]
Values <= 8: [5 3 8]


In [8]:
(6)
A = np.array([10, 15, 20, 25, 30, 35])

result = A[(A > 15) & (A % 5 == 0)]

print(result)


[20 25 30 35]


In [9]:
(7)
A = np.array([3, -2, 0, 5, -7, 8])

non_negative = A[A >= 0]
negative_count = np.sum(A < 0)

print("Non-negative values:", non_negative)
print("Negative count:", negative_count)

Non-negative values: [3 0 5 8]
Negative count: 2


In [10]:
(8) #boolean replacement
A = np.array([1, 2, 3, 4, 5, 6, 7])

A[A % 2 != 0] = -1

print(A)

[-1  2 -1  4 -1  6 -1]


 PART:C Fancy Indexing

In [11]:
(9) #index list selection
A = np.array([11, 22, 33, 44, 55, 66])

print(A[[1, 3, 5]])

[22 44 66]


In [12]:
(10) #rearranging elements
A = np.array([100, 200, 300, 400, 500])

print(A[[4, 2, 0]])

[500 300 100]


In [13]:
(11) #fancy indexing on 2d array
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(M[[0, 1, 2], [0, 1, 2]])

[1 5 9]


In [14]:
(12) #Row Recording
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(M[[2, 0]])

[[7 8 9]
 [1 2 3]]


PART D: Boolean Indexing vs np.where()

In [15]:
(13) #filtering vs transforming
A = np.array([4, 9, 2, 7, 12, 3])

filtered = A[A > 5]
transformed = np.where(A > 5, 1, 0)

print("Boolean indexing:", filtered)
print("np.where:", transformed)

Boolean indexing: [ 9  7 12]
np.where: [0 1 0 1 1 0]


In [16]:
(14) #replace negavites-two methods(1.Boolean indexing)
A = np.array([-5, 10, -3, 8, -1])

B = A.copy()
B[B < 0] = 0

print(B)

[ 0 10  0  8  0]


In [17]:
(14) #(2.np.where)
A = np.array([-5, 10, -3, 8, -1])

B = np.where(A < 0, 0, A)

print(B)

[ 0 10  0  8  0]


In [18]:
(15) #Labeling Data with np.where
scores = np.array([45, 60, 30, 85, 90])

filtered_scores = scores[scores >= 50]

labels = np.where(scores >= 50, "Pass", "Fail")

print("Filtered scores:", filtered_scores)
print("Labels:", labels)

Filtered scores: [60 85 90]
Labels: ['Fail' 'Pass' 'Fail' 'Pass' 'Pass']


PART E:Broadcasting

In [19]:
(16) #Row-wise Broadcasting
M = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

A = np.array([10, 20, 30])

print("Addition:")
print(M + A)

print("Subtraction:")
print(M - A)

Addition:
[[11 22 33]
 [14 25 36]]
Subtraction:
[[ -9 -18 -27]
 [ -6 -15 -24]]


In [20]:
(17) #Row Normalizatuon
M = np.array([
    [2, 4],
    [6, 8]
])

A = np.array([2, 2])

print(M / A)

[[1. 2.]
 [3. 4.]]


In [21]:
(18) #Scalar Broadcasting
A = np.array([10, 20, 30])

print(A + 5)

[15 25 35]


In [22]:
(19) # Boolean vs np.where() on 2D
M = np.array([
    [5, 10, 15],
    [20, 25, 30]
])

In [23]:
 #Boolean indexing
A = M.copy()
A[A > 20] = 20

print(A)

[[ 5 10 15]
 [20 20 20]]


In [24]:
# np.where()
B = np.where(M > 20, 20, M)

print(B)

[[ 5 10 15]
 [20 20 20]]


In [25]:
(20) #Broadcasting Concept Check
M = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

A = np.array([10, 20])

result = M + A

print(result)

[[11 22]
 [13 24]
 [15 26]]
